### PR TITLE
[OCF-73][OCF-74] core/invoker and core/controller: switch to CentOS 7

### PR DESCRIPTION
**Pull request by goldmann**
https://issues.jboss.org/browse/OCF-73
https://issues.jboss.org/browse/OCF-74

### CODE REVIEW

**Comment by goldmann** [comment]
@jcrossley3 I've investigated the failure and reproduced it locally. Unfortunately the same issue exists even with current `rhdemo` branch, so my changes are not related to this failure.

**Comment by jcrossley3** [comment]
@goldmann if you run the `tools/vagrant/hello` script, you'll see that it runs fine with rhdemo, but not with your change. *something* is different, because the ansible script is unable to recognize that the controller is up.

**Comment by goldmann** [comment]
I can reproduce this error locally with vagrant, I'll try to find the root cause.

**Comment by goldmann** [comment]
Investigation of CI failure below.

Invoker containers are failing on Travis because of file permission issues:

```
cp: cannot create regular file '/opt/jboss/jmxremote.access': Permission denied
cp: cannot create regular file '/opt/jboss/jmxremote.password': Permission denied
chmod: cannot access '/opt/jboss/jmxremote.*': No such file or directory
Error: Password file not found: /opt/jboss/jmxremote.password
```

The user that is used to run the `copyJMXFiles.sh` file is using id `1000` and this is the `jboss` user:

```
uid=1000(jboss) gid=1000(jboss) groups=1000(jboss)
```

Files stored in `/conf` are owned by user with id `2000`, but access is `777`, so anyone can read or modify it.

```
total 16K
drwxrwxrwx 2   2000   2000 4.0K Apr  9 14:13 .
drwxr-xr-x 1 493216 493216 4.0K Apr  9 14:13 ..
-rwxrwxrwx 1   2000   2000   18 Apr  9 14:13 jmxremote.access
-rwxrwxrwx 1   2000   2000   16 Apr  9 14:13 jmxremote.password
```

The destination path is owned by (random) user with id `494216`:

```
total 20K
drwxr-xr-x  2 494216 494216 4.0K Apr  9 14:12 .
drwxr-xr-x  3 493216 493216 4.0K Apr  9 14:12 ..
-rw-r--r-- 14 494216 494216   18 Sep  6  2017 .bash_logout
-rw-r--r-- 14 494216 494216  193 Sep  6  2017 .bash_profile
-rw-r--r-- 14 494216 494216  231 Sep  6  2017 .bashrc
```

Considering all above it's obvious that this script cannot work as is since the user that runs the script does not have permissions to write to `/opt/jboss` directory.

**Pull request merged**
